#!/bin/sh

PATH=/opt/polyspaceR2019a/polyspace/bin/:$PATH

	
INCLUDE=`realpath ../include`

polyspace-bug-finder-nodesktop \
    -checkers all \
    -disable-checkers tainted_data \
    -I ${INCLUDE} \
    -I ${INCLUDE}/openssl \
    -D SIXTY_FOUR_BIT_LONG \
    -D OPENSSL_NO_KRB5 \
    -keep-all-files \
    -sources symmetric_cipher.c \
    -results-dir RESULT \
    $@
(cd RESULT; polyspace)& 
